import { createFileRoute } from "@tanstack/react-router";
import JvzooSalesPage from "~/components/JvzooSalesPage";
import { getProductBySlug } from "~/data/products";

const product = getProductBySlug("genesis-platform")!;
export const Route = createFileRoute("/jvzoo/genesis")({
  head: () => ({ meta: [{ title: "Genesis Platform | PrismBay JVZoo Offer" }, { name: "description", content: "Build AI-powered business applications from a single description with the Genesis Platform blueprint." }] }),
  component: () => <JvzooSalesPage config={{ productKey: "genesis", product, tagline: "Build AI-powered business applications from a single description", audience: "Genesis Platform is built for technical founders, product builders, and SaaS entrepreneurs who want to create the next generation of AI application platforms. Use the blueprint to give your engineering team a clear path from prompt-to-application concept to a commercial, multi-tenant product.", features: [{ title: "Prompt-to-application workflow", description: "Map the experience that turns a natural-language description into a structured, configurable business application." }, { title: "No-code builder foundation", description: "Plan templates, forms, dashboards, data models, and workflow controls that let customers build without writing code." }, { title: "AI agent builder", description: "Design the agent orchestration layer, permissions, human approval controls, and reusable AI capabilities." }, { title: "Commercial platform model", description: "Launch with template marketplace mechanics, subscriptions, payments, and an enterprise licensing strategy." }], faq: [{ question: "What does the Genesis Platform blueprint cover?", answer: "It covers the prompt-to-application journey, no-code builder, workflow automation, AI agents, templates, data, authentication, payments, subscriptions, and launch planning." }, { question: "Who can implement this system?", answer: "A product founder can use the business and product sections, while a technical co-founder or engineering team can use the architecture and roadmap to plan implementation." }, { question: "Is enterprise licensing included?", answer: "Yes. The package includes an enterprise licensing strategy alongside the core product and subscription model." }] }} />,
});
