import { createFileRoute } from "@tanstack/react-router";
import JvzooSalesPage from "~/components/JvzooSalesPage";
import { getProductBySlug } from "~/data/products";

const product = getProductBySlug("nexus-network")!;
export const Route = createFileRoute("/jvzoo/nexus")({
  head: () => ({ meta: [{ title: "Nexus Network | PrismBay JVZoo Offer" }, { name: "description", content: "Launch an AI-powered business collaboration marketplace with the Nexus Network blueprint." }] }),
  component: () => <JvzooSalesPage config={{ productKey: "nexus", product, tagline: "Launch an AI-powered business collaboration marketplace", audience: "Nexus Network is for platform founders, community builders, and marketplace entrepreneurs who want to connect businesses, professionals, and service providers in a trusted B2B environment. Build from a proven product, trust, and commission-model foundation instead of starting with a blank page.", features: [{ title: "Intelligent matching", description: "Define profiles, recommendation logic, search, and filters that help the right businesses and providers find one another." }, { title: "Project workflows", description: "Structure opportunity listings, collaboration requests, messaging, and project coordination from first contact through delivery." }, { title: "Marketplace controls", description: "Plan moderation, listings, roles, permissions, reviews, and operational controls for a dependable marketplace experience." }, { title: "Trust and commission model", description: "Build verification and ratings into the product while mapping transaction fees, subscriptions, featured listings, and premium services." }], faq: [{ question: "What kind of marketplace can I build with Nexus Network?", answer: "The blueprint is designed for B2B collaboration marketplaces connecting businesses with professionals, service providers, AI solutions, and technology partners." }, { question: "How does the revenue model work?", answer: "The package includes models for transaction commissions, subscription tiers, featured listings, and premium marketplace services." }, { question: "What is the estimated MVP timeline?", answer: "The implementation roadmap estimates 12–16 weeks to MVP for a team of two to three engineers plus a business lead." }] }} />,
});
