import { createFileRoute } from "@tanstack/react-router";
import JvzooSalesPage from "~/components/JvzooSalesPage";
import { BUNDLES } from "~/data/products";

const product = BUNDLES.find((bundle) => bundle.slug === "complete-portfolio")!;
export const Route = createFileRoute("/jvzoo/portfolio")({
  head: () => ({ meta: [{ title: "Complete AI Business Portfolio | PrismBay JVZoo Offer" }, { name: "description", content: "Get all 9 PrismBay AI business system blueprints in one complete portfolio." }] }),
  component: () => <JvzooSalesPage config={{ productKey: "portfolio", product, tagline: "The complete collection of 9 AI business systems", audience: "The Complete Portfolio is for serious business builders, agencies, and investors who want a broad, ready-to-evaluate collection of AI-native ventures. Cover every major business function with one purchase, then choose which systems to build, license, or bring to clients under the appropriate commercial licence.", features: [{ title: "All 9 systems", description: "Get Genesis Platform, Nexus Network, NexusOS, Nexus One, Empire AI, Digital Humans, GuardianOS, SpendShield AI, and EvidenceFlow AI." }, { title: "Every business function", description: "Explore product blueprints spanning application development, operations, collaboration, workforce, trust, procurement, compliance, and executive management." }, { title: "One purchase, one foundation", description: "Receive the complete documentation collection in one coordinated portfolio instead of assembling systems one at a time." }, { title: "Best portfolio value", description: "Save $1,542 compared with the combined regular price and gain a complete pipeline of concepts to assess and build." }], faq: [{ question: "What is included in the Complete Portfolio?", answer: "All 9 PrismBay AI business system blueprints, including documentation for product strategy, workflows, architecture, revenue models, and launch guidance." }, { question: "Can I build all 9 products under one licence?", answer: "The portfolio gives you the complete collection, but each system remains subject to its applicable single-business licence. Review the licence terms before implementation or agency use." }, { question: "Who benefits most from the portfolio?", answer: "Serious founders, agencies with appropriate licensing, investors, and venture builders evaluating multiple AI business opportunities benefit most from the breadth of the collection." }] }} />,
});
