import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {videos,metadata,channelId} from './revenue-ai-content.mjs';
import {verifyProbe} from './render-revenue-ai.mjs';
test('only correct AI channel and canonical product with distinct UTMs',()=>{const urls=new Set();for(const v of videos){const m=metadata(v),u=new URL(m.url);assert.equal(m.channelId,'UCw2hs85TzIpdKwJtG-BSxzQ');assert.equal(u.hostname,'www.prismbayai.com');assert.equal(u.pathname,'/products/spendshield-ai');assert.equal(u.searchParams.get('utm_source'),'youtube');urls.add(m.url);assert.equal(m.status,'DRAFT_BLOCKED_DELIVERY');assert.match(m.description,/DOCUMENT BLUEPRINT/);}assert.equal(urls.size,2);});
test('timing, hook and blueprint disclosure',()=>{for(const v of videos){const d=v.scenes.reduce((n,s)=>n+s.seconds,0);assert.ok(d>=15&&d<=35);assert.ok(v.scenes[0].title.length<65);assert.match(v.scenes.at(-1).label,/DOCUMENT BLUEPRINT/);assert.match(v.scenes.at(-1).rows.join(' '),/249/);for(const s of v.scenes)for(const row of s.rows)assert.ok(row.length<=40);}});
test('price matches repository catalog and payment map',()=>{const c=fs.readFileSync(new URL('../src/data/products.ts',import.meta.url),'utf8');assert.match(c,/slug: "spendshield-ai",[\s\S]*?launchPrice: 249/);assert.match(fs.readFileSync(new URL('../src/data/payment-links.ts',import.meta.url),'utf8'),/"spendshield-ai"[^\n]*\$249/);});
test('probe gate rejects wrong size, duration, codec and oversized files',()=>{const p={streams:[{codec_type:'video',width:1080,height:1920,codec_name:'h264',pix_fmt:'yuv420p'}],format:{duration:'30',size:'500000'}};assert.equal(verifyProbe(p),30);for(const change of [{duration:'14'},{duration:'36'},{size:'10000001'}])assert.throws(()=>verifyProbe({...p,format:{...p.format,...change}}));assert.throws(()=>verifyProbe({...p,streams:[{...p.streams[0],width:720}]}));assert.throws(()=>verifyProbe({...p,streams:[{...p.streams[0],codec_name:'vp9'}]}));});
